### ISSUE TITLE
4.1.0 macOS build broken?

### ISSUE THREAD

**Issue by pauldmccarthy** [conda-forge/wxpython-feedstock#70] opened 2021-02-02 13:01 UTC
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Howdy, I seem to be having some trouble with the wxpython 4.1.0 conda-forge builds on macOS - to reproduce:

```
$ cd ~
$ conda create -p ./test-env -c conda-forge wxpython
```

<details>

```
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/paulmc/test-env

  added / updated specs:
    - wxpython


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    backports.lzma-0.0.14      |   py39hd5dad98_3          48 KB  conda-forge
    brotlipy-0.7.0             |py39hcbf5805_1001         357 KB  conda-forge
    certifi-2020.12.5          |   py39h6e9494a_1         143 KB  conda-forge
    cffi-1.14.4                |   py39h7786acb_1         219 KB  conda-forge
    chardet-4.0.0              |   py39h6e9494a_1         204 KB  conda-forge
    cryptography-3.3.1         |   py39h79a2c39_1         612 KB  conda-forge
    pathlib2-2.3.5             |   py39h6e9494a_3          35 KB  conda-forge
    pysocks-1.7.1              |   py39h6e9494a_3          27 KB  conda-forge
    python-3.9.1               |h2502468_5_cpython        12.6 MB  conda-forge
    python.app-1.3             |   py39hcbf5805_4          12 KB  conda-forge
    python_abi-3.9             |           1_cp39           4 KB  conda-forge
    setuptools-49.6.0          |   py39h6e9494a_3         950 KB  conda-forge
    tzdata-2021a               |       he74cb21_0         121 KB  conda-forge
    wxpython-4.1.0             |   py39hcb38c71_4        28.6 MB  conda-forge
    ------------------------------------------------------------
                                           Total:        43.9 MB

The following NEW packages will be INSTALLED:

  backports          conda-forge/noarch::backports-1.0-py_2
  backports.lzma     conda-forge/osx-64::backports.lzma-0.0.14-py39hd5dad98_3
  brotlipy           conda-forge/osx-64::brotlipy-0.7.0-py39hcbf5805_1001
  ca-certificates    conda-forge/osx-64::ca-certificates-2020.12.5-h033912b_0
  certifi            conda-forge/osx-64::certifi-2020.12.5-py39h6e9494a_1
  cffi               conda-forge/osx-64::cffi-1.14.4-py39h7786acb_1
  chardet            conda-forge/osx-64::chardet-4.0.0-py39h6e9494a_1
  cryptography       conda-forge/osx-64::cryptography-3.3.1-py39h79a2c39_1
  expat              conda-forge/osx-64::expat-2.2.10-h1c7c35f_0
  gettext            conda-forge/osx-64::gettext-0.19.8.1-h7937167_1005
  idna               conda-forge/noarch::idna-2.10-pyh9f0ad1d_0
  jpeg               conda-forge/osx-64::jpeg-9d-hbcb3906_0
  libcxx             conda-forge/osx-64::libcxx-11.0.1-habf9029_0
  libffi             conda-forge/osx-64::libffi-3.3-h046ec9c_2
  libiconv           conda-forge/osx-64::libiconv-1.16-haf1e3a3_0
  libpng             conda-forge/osx-64::libpng-1.6.37-h7cec526_2
  ncurses            conda-forge/osx-64::ncurses-6.2-h2e338ed_4
  openssl            conda-forge/osx-64::openssl-1.1.1i-h35c211d_0
  pathlib2           conda-forge/osx-64::pathlib2-2.3.5-py39h6e9494a_3
  pip                conda-forge/noarch::pip-21.0.1-pyhd8ed1ab_0
  pthread-stubs      conda-forge/osx-64::pthread-stubs-0.4-hc929b4f_1001
  pycparser          conda-forge/noarch::pycparser-2.20-pyh9f0ad1d_2
  pyopenssl          conda-forge/noarch::pyopenssl-20.0.1-pyhd8ed1ab_0
  pypubsub           conda-forge/noarch::pypubsub-4.0.3-py_0
  pysocks            conda-forge/osx-64::pysocks-1.7.1-py39h6e9494a_3
  python             conda-forge/osx-64::python-3.9.1-h2502468_5_cpython
  python.app         conda-forge/osx-64::python.app-1.3-py39hcbf5805_4
  python_abi         conda-forge/osx-64::python_abi-3.9-1_cp39
  readline           conda-forge/osx-64::readline-8.0-h0678c8f_2
  requests           conda-forge/noarch::requests-2.25.1-pyhd3deb0d_0
  setuptools         conda-forge/osx-64::setuptools-49.6.0-py39h6e9494a_3
  six                conda-forge/noarch::six-1.15.0-pyh9f0ad1d_0
  sqlite             conda-forge/osx-64::sqlite-3.34.0-h17101e1_0
  tk                 conda-forge/osx-64::tk-8.6.10-h0419947_1
  tzdata             conda-forge/noarch::tzdata-2021a-he74cb21_0
  urllib3            conda-forge/noarch::urllib3-1.26.3-pyhd8ed1ab_0
  wheel              conda-forge/noarch::wheel-0.36.2-pyhd3deb0d_0
  wxpython           conda-forge/osx-64::wxpython-4.1.0-py39hcb38c71_4
  xz                 conda-forge/osx-64::xz-5.2.5-haf1e3a3_1
  zlib               conda-forge/osx-64::zlib-1.2.11-h7795811_1010


Proceed ([y]/n)? y


Downloading and Extracting Packages
chardet-4.0.0        | 204 KB    | #################################################################################### | 100%
setuptools-49.6.0    | 950 KB    | #################################################################################### | 100%
backports.lzma-0.0.1 | 48 KB     | #################################################################################### | 100%
wxpython-4.1.0       | 28.6 MB   | ##################################9                                                  |  42% wxpython-4.1.0       | 28.6 MB   | ###########################################5                                         |  52% wxpython-4.1.0       | 28.6 MB   | ####################################################                                 |  62% wxpython-4.1.0       | 28.6 MB   | ####################################################################9                |  82% wxpython-4.1.0       | 28.6 MB   | #############################################################################1       |  92% wxpython-4.1.0       | 28.6 MB   | #################################################################################### | 100%
python-3.9.1         | 12.6 MB   | #################################################################################### | 100%
tzdata-2021a         | 121 KB    | #################################################################################### | 100%
certifi-2020.12.5    | 143 KB    | #################################################################################### | 100%
cryptography-3.3.1   | 612 KB    | #################################################################################### | 100%
python.app-1.3       | 12 KB     | #################################################################################### | 100%
python_abi-3.9       | 4 KB      | #################################################################################### | 100%
cffi-1.14.4          | 219 KB    | #################################################################################### | 100%
pysocks-1.7.1        | 27 KB     | #################################################################################### | 100%
pathlib2-2.3.5       | 35 KB     | #################################################################################### | 100%
brotlipy-0.7.0       | 357 KB    | #################################################################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate /Users/paulmc/test-env
#
# To deactivate an active environment, use
#
#     $ conda deactivate
```
</details>
<br/>

```
$ source activate ./test-env
# just to double check that we're using the correct interpreter
$ which pythonw
/Users/paulmc/test-env/bin/pythonw
$ pythonw
```

Then, in the python interpreter:

```
Python 3.9.1 | packaged by conda-forge | (default, Jan 26 2021, 01:32:59)
[Clang 11.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import wx
>>> app = wx.App()
/Users/paulmc/test-env/bin/pythonw: line 3: 97001 Segmentation fault: 11  /Users/paulmc/test-env/python.app/Contents/MacOS/python "$@"
$
```

Creating an environment with `4.0.7.post2` works fine:

```
$ source deactivate
$ rm -r test-env
$ conda create -p ./test-env -c conda-forge "wxpython=4.0.*"
```

<details>

```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/paulmc/test-env

  added / updated specs:
    - wxpython=4.0


The following NEW packages will be INSTALLED:

  backports          conda-forge/noarch::backports-1.0-py_2
  backports.lzma     conda-forge/osx-64::backports.lzma-0.0.14-py38hba84461_3
  brotlipy           conda-forge/osx-64::brotlipy-0.7.0-py38h5406a74_1001
  ca-certificates    conda-forge/osx-64::ca-certificates-2020.12.5-h033912b_0
  certifi            conda-forge/osx-64::certifi-2020.12.5-py38h50d1736_1
  cffi               conda-forge/osx-64::cffi-1.14.4-py38h979bc6b_1
  chardet            conda-forge/osx-64::chardet-4.0.0-py38h50d1736_1
  cryptography       conda-forge/osx-64::cryptography-3.3.1-py38h6b4ec92_1
  expat              conda-forge/osx-64::expat-2.2.10-h1c7c35f_0
  gettext            conda-forge/osx-64::gettext-0.19.8.1-h7937167_1005
  idna               conda-forge/noarch::idna-2.10-pyh9f0ad1d_0
  jpeg               conda-forge/osx-64::jpeg-9d-hbcb3906_0
  libcxx             conda-forge/osx-64::libcxx-11.0.1-habf9029_0
  libffi             conda-forge/osx-64::libffi-3.3-h046ec9c_2
  libiconv           conda-forge/osx-64::libiconv-1.16-haf1e3a3_0
  libpng             conda-forge/osx-64::libpng-1.6.37-h7cec526_2
  ncurses            conda-forge/osx-64::ncurses-6.2-h2e338ed_4
  openssl            conda-forge/osx-64::openssl-1.1.1i-h35c211d_0
  pathlib2           conda-forge/osx-64::pathlib2-2.3.5-py38h50d1736_3
  pip                conda-forge/noarch::pip-21.0.1-pyhd8ed1ab_0
  pthread-stubs      conda-forge/osx-64::pthread-stubs-0.4-hc929b4f_1001
  pycparser          conda-forge/noarch::pycparser-2.20-pyh9f0ad1d_2
  pyopenssl          conda-forge/noarch::pyopenssl-20.0.1-pyhd8ed1ab_0
  pypubsub           conda-forge/noarch::pypubsub-4.0.3-py_0
  pysocks            conda-forge/osx-64::pysocks-1.7.1-py38h50d1736_3
  python             conda-forge/osx-64::python-3.8.6-h624753d_5_cpython
  python.app         conda-forge/osx-64::python.app-1.3-py38h5406a74_4
  python_abi         conda-forge/osx-64::python_abi-3.8-1_cp38
  readline           conda-forge/osx-64::readline-8.0-h0678c8f_2
  requests           conda-forge/noarch::requests-2.25.1-pyhd3deb0d_0
  setuptools         conda-forge/osx-64::setuptools-49.6.0-py38h50d1736_3
  six                conda-forge/noarch::six-1.15.0-pyh9f0ad1d_0
  sqlite             conda-forge/osx-64::sqlite-3.34.0-h17101e1_0
  tk                 conda-forge/osx-64::tk-8.6.10-h0419947_1
  urllib3            conda-forge/noarch::urllib3-1.26.3-pyhd8ed1ab_0
  wheel              conda-forge/noarch::wheel-0.36.2-pyhd3deb0d_0
  wxpython           conda-forge/osx-64::wxpython-4.0.7.post2-py38h10bb4de_3
  xz                 conda-forge/osx-64::xz-5.2.5-haf1e3a3_1
  zlib               conda-forge/osx-64::zlib-1.2.11-h7795811_1010


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate /Users/paulmc/test-env
#
# To deactivate an active environment, use
#
#     $ conda deactivate
```
</details>

```
$ source activate ./test-env
$ pythonw
Python 3.8.6 | packaged by conda-forge | (default, Jan 25 2021, 23:22:12)
[Clang 11.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import wx
>>> app = wx.App()
>>> frame = wx.Frame(None)
>>> frame.Show()
True
>>> app.MainLoop()  # I get a frame
^C
$
```

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
(/Users/paulmc/test-env) PMcMBPr15:~ paulmc$ conda list
# packages in environment at /Users/paulmc/test-env:
#
# Name                    Version                   Build  Channel
backports                 1.0                        py_2    conda-forge
backports.lzma            0.0.14           py39hd5dad98_3    conda-forge
brotlipy                  0.7.0           py39hcbf5805_1001    conda-forge
ca-certificates           2020.12.5            h033912b_0    conda-forge
certifi                   2020.12.5        py39h6e9494a_1    conda-forge
cffi                      1.14.4           py39h7786acb_1    conda-forge
chardet                   4.0.0            py39h6e9494a_1    conda-forge
cryptography              3.3.1            py39h79a2c39_1    conda-forge
expat                     2.2.10               h1c7c35f_0    conda-forge
gettext                   0.19.8.1          h7937167_1005    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
jpeg                      9d                   hbcb3906_0    conda-forge
libcxx                    11.0.1               habf9029_0    conda-forge
libffi                    3.3                  h046ec9c_2    conda-forge
libiconv                  1.16                 haf1e3a3_0    conda-forge
libpng                    1.6.37               h7cec526_2    conda-forge
ncurses                   6.2                  h2e338ed_4    conda-forge
openssl                   1.1.1i               h35c211d_0    conda-forge
pathlib2                  2.3.5            py39h6e9494a_3    conda-forge
pip                       21.0.1             pyhd8ed1ab_0    conda-forge
pthread-stubs             0.4               hc929b4f_1001    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pypubsub                  4.0.3                      py_0    conda-forge
pysocks                   1.7.1            py39h6e9494a_3    conda-forge
python                    3.9.1           h2502468_5_cpython    conda-forge
python.app                1.3              py39hcbf5805_4    conda-forge
python_abi                3.9                      1_cp39    conda-forge
readline                  8.0                  h0678c8f_2    conda-forge
requests                  2.25.1             pyhd3deb0d_0    conda-forge
setuptools                49.6.0           py39h6e9494a_3    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.34.0               h17101e1_0    conda-forge
tk                        8.6.10               h0419947_1    conda-forge
tzdata                    2021a                he74cb21_0    conda-forge
urllib3                   1.26.3             pyhd8ed1ab_0    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
wxpython                  4.1.0            py39hcb38c71_4    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
zlib                      1.2.11            h7795811_1010    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : /Users/paulmc/test-env
    active env location : /Users/paulmc/test-env
            shell level : 1
       user config file : /Users/paulmc/.condarc
 populated config files : /Users/paulmc/.conda/condarc
                          /Users/paulmc/.condarc
          conda version : 4.9.2
    conda-build version : 3.21.4
         python version : 3.8.6.final.0
       virtual packages : __osx=10.15.7=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/paulmc/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/paulmc/miniconda3/pkgs
                          /Users/paulmc/.conda/pkgs
       envs directories : /Users/paulmc/miniconda3/envs
                          /Users/paulmc/.conda/envs
               platform : osx-64
             user-agent : conda/4.9.2 requests/2.25.1 CPython/3.8.6 Darwin/19.6.0 OSX/10.15.7
                UID:GID : 503:20
             netrc file : None
           offline mode : False
```
</details>

**Comment by Colelyman** [comment] 2021-02-02 17:50
I was running into similar issues too! Before it segfaulted I got the warning that classes were implemented in two shared libraries (see https://github.com/wxFormBuilder/wxFormBuilder/issues/340 for a more in depth explanation).

I was able to resolve things by completely removing my conda environment and starting fresh. I wonder if perhaps there was an update and the shared libraries from a previous version didn't get completely removed... I don't know enough about the library to know if there is a more insidious bug in how it is being built, but I thought I would share how I resolved a similar issue.

**Comment by pauldmccarthy** [comment] 2021-02-03 09:40
@Colelyman, can you confirm that your newly created environment contains wpxpython 4.1.0? I can reproduce the problem with a fresh miniconda install:



```
$ export PATH=/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
$ wget https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
```

<details>

```
--2021-02-03 09:34:41--  https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
Resolving repo.anaconda.com... 104.16.130.3, 104.16.131.3
Connecting to repo.anaconda.com|104.16.130.3|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 57112343 (54M) [application/x-sh]
Saving to: ‘Miniconda3-latest-MacOSX-x86_64.sh’

Miniconda3-latest-MacOSX-x86_64 100%[======================================================>]  54.47M  92.4MB/s    in 0.6s

2021-02-03 09:34:41 (92.4 MB/s) - ‘Miniconda3-latest-MacOSX-x86_64.sh’ saved [57112343/57112343]
```
</details>

```
$ sh ./Miniconda3-latest-MacOSX-x86_64.sh -b -p ./test-miniconda
```

<details>

```
PREFIX=/Users/paulmc/test-miniconda
Unpacking payload ...
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/paulmc/test-miniconda

  added / updated specs:
    - brotlipy==0.7.0=py38h9ed2024_1003
    - ca-certificates==2020.10.14=0
    - certifi==2020.6.20=pyhd3eb1b0_3
    - cffi==1.14.3=py38h2125817_2
    - chardet==3.0.4=py38hecd8cb5_1003
    - conda-package-handling==1.7.2=py38h22f3db7_0
    - conda==4.9.2=py38hecd8cb5_0
    - cryptography==3.2.1=py38hbcfaee0_1
    - idna==2.10=py_0
    - libcxx==10.0.0=1
    - libedit==3.1.20191231=h1de35cc_1
    - libffi==3.3=hb1e8313_2
    - ncurses==6.2=h0a44026_1
    - openssl==1.1.1h=haf1e3a3_0
    - pip==20.2.4=py38hecd8cb5_0
    - pycosat==0.6.3=py38h1de35cc_1
    - pycparser==2.20=py_2
    - pyopenssl==19.1.0=pyhd3eb1b0_1
    - pysocks==1.7.1=py38_1
    - python.app==2=py38_10
    - python==3.8.5=h26836e1_1
    - readline==8.0=h1de35cc_0
    - requests==2.24.0=py_0
    - ruamel_yaml==0.15.87=py38haf1e3a3_1
    - setuptools==50.3.1=py38hecd8cb5_1
    - six==1.15.0=py38hecd8cb5_0
    - sqlite==3.33.0=hffcf06c_0
    - tk==8.6.10=hb0a8c7a_0
    - tqdm==4.51.0=pyhd3eb1b0_0
    - urllib3==1.25.11=py_0
    - wheel==0.35.1=pyhd3eb1b0_0
    - xz==5.2.5=h1de35cc_0
    - yaml==0.2.5=haf1e3a3_0
    - zlib==1.2.11=h1de35cc_3


The following NEW packages will be INSTALLED:

  brotlipy           pkgs/main/osx-64::brotlipy-0.7.0-py38h9ed2024_1003
  ca-certificates    pkgs/main/osx-64::ca-certificates-2020.10.14-0
  certifi            pkgs/main/noarch::certifi-2020.6.20-pyhd3eb1b0_3
  cffi               pkgs/main/osx-64::cffi-1.14.3-py38h2125817_2
  chardet            pkgs/main/osx-64::chardet-3.0.4-py38hecd8cb5_1003
  conda              pkgs/main/osx-64::conda-4.9.2-py38hecd8cb5_0
  conda-package-han~ pkgs/main/osx-64::conda-package-handling-1.7.2-py38h22f3db7_0
  cryptography       pkgs/main/osx-64::cryptography-3.2.1-py38hbcfaee0_1
  idna               pkgs/main/noarch::idna-2.10-py_0
  libcxx             pkgs/main/osx-64::libcxx-10.0.0-1
  libedit            pkgs/main/osx-64::libedit-3.1.20191231-h1de35cc_1
  libffi             pkgs/main/osx-64::libffi-3.3-hb1e8313_2
  ncurses            pkgs/main/osx-64::ncurses-6.2-h0a44026_1
  openssl            pkgs/main/osx-64::openssl-1.1.1h-haf1e3a3_0
  pip                pkgs/main/osx-64::pip-20.2.4-py38hecd8cb5_0
  pycosat            pkgs/main/osx-64::pycosat-0.6.3-py38h1de35cc_1
  pycparser          pkgs/main/noarch::pycparser-2.20-py_2
  pyopenssl          pkgs/main/noarch::pyopenssl-19.1.0-pyhd3eb1b0_1
  pysocks            pkgs/main/osx-64::pysocks-1.7.1-py38_1
  python             pkgs/main/osx-64::python-3.8.5-h26836e1_1
  python.app         pkgs/main/osx-64::python.app-2-py38_10
  readline           pkgs/main/osx-64::readline-8.0-h1de35cc_0
  requests           pkgs/main/noarch::requests-2.24.0-py_0
  ruamel_yaml        pkgs/main/osx-64::ruamel_yaml-0.15.87-py38haf1e3a3_1
  setuptools         pkgs/main/osx-64::setuptools-50.3.1-py38hecd8cb5_1
  six                pkgs/main/osx-64::six-1.15.0-py38hecd8cb5_0
  sqlite             pkgs/main/osx-64::sqlite-3.33.0-hffcf06c_0
  tk                 pkgs/main/osx-64::tk-8.6.10-hb0a8c7a_0
  tqdm               pkgs/main/noarch::tqdm-4.51.0-pyhd3eb1b0_0
  urllib3            pkgs/main/noarch::urllib3-1.25.11-py_0
  wheel              pkgs/main/noarch::wheel-0.35.1-pyhd3eb1b0_0
  xz                 pkgs/main/osx-64::xz-5.2.5-h1de35cc_0
  yaml               pkgs/main/osx-64::yaml-0.2.5-haf1e3a3_0
  zlib               pkgs/main/osx-64::zlib-1.2.11-h1de35cc_3


Preparing transaction: done
Executing transaction: done
installation finished.
```
</details>

```
$ export PATH=$(pwd)/test-miniconda/bin:$PATH
$ conda create -y -c conda-forge -p ./test-env wxpython
```

<details>

```
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/paulmc/test-env

  added / updated specs:
    - wxpython


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    backports-1.0              |             py_2           4 KB  conda-forge
    backports.lzma-0.0.14      |   py39hd5dad98_3          48 KB  conda-forge
    brotlipy-0.7.0             |py39hcbf5805_1001         357 KB  conda-forge
    ca-certificates-2020.12.5  |       h033912b_0         138 KB  conda-forge
    certifi-2020.12.5          |   py39h6e9494a_1         143 KB  conda-forge
    cffi-1.14.4                |   py39h7786acb_1         219 KB  conda-forge
    chardet-4.0.0              |   py39h6e9494a_1         204 KB  conda-forge
    cryptography-3.3.1         |   py39h79a2c39_1         612 KB  conda-forge
    expat-2.2.10               |       h1c7c35f_0         128 KB  conda-forge
    gettext-0.19.8.1           |    h7937167_1005         3.3 MB  conda-forge
    idna-2.10                  |     pyh9f0ad1d_0          52 KB  conda-forge
    jpeg-9d                    |       hbcb3906_0         250 KB  conda-forge
    libcxx-11.0.1              |       habf9029_0         1.0 MB  conda-forge
    libffi-3.3                 |       h046ec9c_2          45 KB  conda-forge
    libiconv-1.16              |       haf1e3a3_0         1.3 MB  conda-forge
    libpng-1.6.37              |       h7cec526_2         313 KB  conda-forge
    ncurses-6.2                |       h2e338ed_4         881 KB  conda-forge
    openssl-1.1.1i             |       h35c211d_0         1.9 MB  conda-forge
    pathlib2-2.3.5             |   py39h6e9494a_3          35 KB  conda-forge
    pip-21.0.1                 |     pyhd8ed1ab_0         1.1 MB  conda-forge
    pthread-stubs-0.4          |    hc929b4f_1001           6 KB  conda-forge
    pycparser-2.20             |     pyh9f0ad1d_2          94 KB  conda-forge
    pyopenssl-20.0.1           |     pyhd8ed1ab_0          48 KB  conda-forge
    pypubsub-4.0.3             |             py_0          44 KB  conda-forge
    pysocks-1.7.1              |   py39h6e9494a_3          27 KB  conda-forge
    python-3.9.1               |h2502468_5_cpython        12.6 MB  conda-forge
    python.app-1.3             |   py39hcbf5805_4          12 KB  conda-forge
    python_abi-3.9             |           1_cp39           4 KB  conda-forge
    readline-8.0               |       h0678c8f_2         255 KB  conda-forge
    requests-2.25.1            |     pyhd3deb0d_0          51 KB  conda-forge
    setuptools-49.6.0          |   py39h6e9494a_3         950 KB  conda-forge
    six-1.15.0                 |     pyh9f0ad1d_0          14 KB  conda-forge
    sqlite-3.34.0              |       h17101e1_0         1.7 MB  conda-forge
    tk-8.6.10                  |       h0419947_1         3.3 MB  conda-forge
    tzdata-2021a               |       he74cb21_0         121 KB  conda-forge
    urllib3-1.26.3             |     pyhd8ed1ab_0          99 KB  conda-forge
    wheel-0.36.2               |     pyhd3deb0d_0          31 KB  conda-forge
    wxpython-4.1.0             |   py39hcb38c71_4        28.6 MB  conda-forge
    xz-5.2.5                   |       haf1e3a3_1         228 KB  conda-forge
    zlib-1.2.11                |    h7795811_1010         102 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        60.1 MB

The following NEW packages will be INSTALLED:

  backports          conda-forge/noarch::backports-1.0-py_2
  backports.lzma     conda-forge/osx-64::backports.lzma-0.0.14-py39hd5dad98_3
  brotlipy           conda-forge/osx-64::brotlipy-0.7.0-py39hcbf5805_1001
  ca-certificates    conda-forge/osx-64::ca-certificates-2020.12.5-h033912b_0
  certifi            conda-forge/osx-64::certifi-2020.12.5-py39h6e9494a_1
  cffi               conda-forge/osx-64::cffi-1.14.4-py39h7786acb_1
  chardet            conda-forge/osx-64::chardet-4.0.0-py39h6e9494a_1
  cryptography       conda-forge/osx-64::cryptography-3.3.1-py39h79a2c39_1
  expat              conda-forge/osx-64::expat-2.2.10-h1c7c35f_0
  gettext            conda-forge/osx-64::gettext-0.19.8.1-h7937167_1005
  idna               conda-forge/noarch::idna-2.10-pyh9f0ad1d_0
  jpeg               conda-forge/osx-64::jpeg-9d-hbcb3906_0
  libcxx             conda-forge/osx-64::libcxx-11.0.1-habf9029_0
  libffi             conda-forge/osx-64::libffi-3.3-h046ec9c_2
  libiconv           conda-forge/osx-64::libiconv-1.16-haf1e3a3_0
  libpng             conda-forge/osx-64::libpng-1.6.37-h7cec526_2
  ncurses            conda-forge/osx-64::ncurses-6.2-h2e338ed_4
  openssl            conda-forge/osx-64::openssl-1.1.1i-h35c211d_0
  pathlib2           conda-forge/osx-64::pathlib2-2.3.5-py39h6e9494a_3
  pip                conda-forge/noarch::pip-21.0.1-pyhd8ed1ab_0
  pthread-stubs      conda-forge/osx-64::pthread-stubs-0.4-hc929b4f_1001
  pycparser          conda-forge/noarch::pycparser-2.20-pyh9f0ad1d_2
  pyopenssl          conda-forge/noarch::pyopenssl-20.0.1-pyhd8ed1ab_0
  pypubsub           conda-forge/noarch::pypubsub-4.0.3-py_0
  pysocks            conda-forge/osx-64::pysocks-1.7.1-py39h6e9494a_3
  python             conda-forge/osx-64::python-3.9.1-h2502468_5_cpython
  python.app         conda-forge/osx-64::python.app-1.3-py39hcbf5805_4
  python_abi         conda-forge/osx-64::python_abi-3.9-1_cp39
  readline           conda-forge/osx-64::readline-8.0-h0678c8f_2
  requests           conda-forge/noarch::requests-2.25.1-pyhd3deb0d_0
  setuptools         conda-forge/osx-64::setuptools-49.6.0-py39h6e9494a_3
  six                conda-forge/noarch::six-1.15.0-pyh9f0ad1d_0
  sqlite             conda-forge/osx-64::sqlite-3.34.0-h17101e1_0
  tk                 conda-forge/osx-64::tk-8.6.10-h0419947_1
  tzdata             conda-forge/noarch::tzdata-2021a-he74cb21_0
  urllib3            conda-forge/noarch::urllib3-1.26.3-pyhd8ed1ab_0
  wheel              conda-forge/noarch::wheel-0.36.2-pyhd3deb0d_0
  wxpython           conda-forge/osx-64::wxpython-4.1.0-py39hcb38c71_4
  xz                 conda-forge/osx-64::xz-5.2.5-haf1e3a3_1
  zlib               conda-forge/osx-64::zlib-1.2.11-h7795811_1010



Downloading and Extracting Packages
pthread-stubs-0.4    | 6 KB      | #################################################################################### | 100%
cryptography-3.3.1   | 612 KB    | #################################################################################### | 100%
idna-2.10            | 52 KB     | #################################################################################### | 100%
wxpython-4.1.0       | 28.6 MB   | #################################################################################### | 100%
readline-8.0         | 255 KB    | #################################################################################### | 100%
pathlib2-2.3.5       | 35 KB     | #################################################################################### | 100%
pycparser-2.20       | 94 KB     | #################################################################################### | 100%
setuptools-49.6.0    | 950 KB    | #################################################################################### | 100%
zlib-1.2.11          | 102 KB    | #################################################################################### | 100%
chardet-4.0.0        | 204 KB    | #################################################################################### | 100%
libpng-1.6.37        | 313 KB    | #################################################################################### | 100%
requests-2.25.1      | 51 KB     | #################################################################################### | 100%
cffi-1.14.4          | 219 KB    | #################################################################################### | 100%
tk-8.6.10            | 3.3 MB    | #################################################################################### | 100%
six-1.15.0           | 14 KB     | #################################################################################### | 100%
gettext-0.19.8.1     | 3.3 MB    | #################################################################################### | 100%
libiconv-1.16        | 1.3 MB    | #################################################################################### | 100%
pip-21.0.1           | 1.1 MB    | #################################################################################### | 100%
urllib3-1.26.3       | 99 KB     | #################################################################################### | 100%
sqlite-3.34.0        | 1.7 MB    | #################################################################################### | 100%
python.app-1.3       | 12 KB     | #################################################################################### | 100%
pysocks-1.7.1        | 27 KB     | #################################################################################### | 100%
backports.lzma-0.0.1 | 48 KB     | #################################################################################### | 100%
certifi-2020.12.5    | 143 KB    | #################################################################################### | 100%
tzdata-2021a         | 121 KB    | #################################################################################### | 100%
python-3.9.1         | 12.6 MB   | #################################################################################### | 100%
ncurses-6.2          | 881 KB    | #################################################################################### | 100%
libffi-3.3           | 45 KB     | #################################################################################### | 100%
pypubsub-4.0.3       | 44 KB     | #################################################################################### | 100%
python_abi-3.9       | 4 KB      | #################################################################################### | 100%
backports-1.0        | 4 KB      | #################################################################################### | 100%
brotlipy-0.7.0       | 357 KB    | #################################################################################### | 100%
expat-2.2.10         | 128 KB    | #################################################################################### | 100%
libcxx-11.0.1        | 1.0 MB    | #################################################################################### | 100%
pyopenssl-20.0.1     | 48 KB     | #################################################################################### | 100%
wheel-0.36.2         | 31 KB     | #################################################################################### | 100%
openssl-1.1.1i       | 1.9 MB    | #################################################################################### | 100%
ca-certificates-2020 | 138 KB    | #################################################################################### | 100%
jpeg-9d              | 250 KB    | #################################################################################### | 100%
xz-5.2.5             | 228 KB    | #################################################################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: /\|/done
#
# To activate this environment, use
#
#     $ conda activate /Users/paulmc/test-env
#
# To deactivate an active environment, use
#
#     $ conda deactivate
```
</details>

```
$ source activate ./test-env
$ pythonw

Python 3.9.1 | packaged by conda-forge | (default, Jan 26 2021, 01:32:59)
[Clang 11.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import wx
>>> app = wx.App()
/Users/paulmc/test-env/bin/pythonw: line 3:  2933 Segmentation fault: 11  /Users/paulmc/test-env/python.app/Contents/MacOS/python "$@"

$ python.app
Python 3.9.1 | packaged by conda-forge | (default, Jan 26 2021, 01:32:59)
[Clang 11.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import wx
>>> app = wx.App()
/Users/paulmc/test-env/bin/python.app: line 3:  2937 Segmentation fault: 11  /Users/paulmc/test-env/python.app/Contents/MacOS/python "$@"
$
```

**Comment by Colelyman** [comment] 2021-02-09 17:59
@pauldmccarthy my mistake! `wxpython==4.1.0` does indeed segfault for me as well. 

Sorry for the confusion, `wxpython==4.0.7.post2` actually was installed in the environment that worked.

**Comment by svniemeijer** [comment] 2021-02-21 10:20
This is likely the same issue as https://trac.macports.org/ticket/61933
The problem is that the package contains binaries for both the 3.1.4.0.0, 3.1.4, 3.1 of the libraries, but the 3.1.4 and 3.1 versions should be symlinks.
Rebuilding the package using the most recent Xcode version should fix the issue.

**Comment by ocefpaf** [comment] 2021-02-24 17:22
Can you test the latest 4.1.1? I just merged one with a bumped macOS SDK and I hope that issue is fixed.

**Comment by pauldmccarthy** [comment] 2021-02-24 19:29
@ocefpaf I haven't tested extensively, but it looks good - thanks!

**Comment by ocefpaf** [comment] 2021-02-24 19:32
Awesome. Closing this for now. Please re-open if the problem persists.

**Closed by ocefpaf** 2021-02-24 19:32 UTC
